### ISSUE TITLE
Specify cancer type in gene_chemokine_heatmap

### ISSUE THREAD

**Issue by xiw588** [tjhwangxiong/TCGAplot#19]
Hi, Is there any efficient way to specify cancer type in gene_chemokine_heatmap, gene_receptor_heatmap, etc. rather than plotting the pan-cancer? 

Thanks

**Comment by tjhwangxiong** [comment]
You could get these data and plot in detail. All data could be extract ED using corresponding functions included.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："xiw588 ***@***.***&gt;;
发送时间：2024年8月7日(星期三) 上午6:12
收件人："tjhwangxiong/TCGAplot" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[tjhwangxiong/TCGAplot] Specify cancer type in gene_chemokine_heatmap (Issue #19)
-----------------------------------

 

 
Hi, Is there any efficient way to specify cancer type in gene_chemokine_heatmap, gene_receptor_heatmap, etc. rather than plotting the pan-cancer?
 
Thanks
